/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_skype_connector_osx_OSXConnector */

#ifndef _Included_com_skype_connector_osx_OSXConnector
#define _Included_com_skype_connector_osx_OSXConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_skype_connector_osx_OSXConnector
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_skype_connector_osx_OSXConnector_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_skype_connector_osx_OSXConnector
 * Method:    startEventLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_skype_connector_osx_OSXConnector_startEventLoop
  (JNIEnv *, jobject);

/*
 * Class:     com_skype_connector_osx_OSXConnector
 * Method:    sendSkypeMessage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_skype_connector_osx_OSXConnector_sendSkypeMessage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_skype_connector_osx_OSXConnector
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_skype_connector_osx_OSXConnector_disposeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_skype_connector_osx_OSXConnector
 * Method:    setDebugPrinting
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_skype_connector_osx_OSXConnector_setDebugPrinting
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
