/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_skype_connector_linux_LinuxConnector */

#ifndef _Included_com_skype_connector_linux_LinuxConnector
#define _Included_com_skype_connector_linux_LinuxConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_skype_connector_linux_LinuxConnector
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_skype_connector_linux_LinuxConnector_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_skype_connector_linux_LinuxConnector
 * Method:    sendSkypeMessage
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_skype_connector_linux_LinuxConnector_sendSkypeMessage
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_skype_connector_linux_LinuxConnector
 * Method:    disposeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_skype_connector_linux_LinuxConnector_disposeNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
