/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_sf_skype_connector_osx_OSXConnector */

#ifndef _Included_jp_sf_skype_connector_osx_OSXConnector
#define _Included_jp_sf_skype_connector_osx_OSXConnector
#ifdef __cplusplus
extern "C" {
#endif
#undef jp_sf_skype_connector_osx_OSXConnector_ATTACH_SUCCESS
#define jp_sf_skype_connector_osx_OSXConnector_ATTACH_SUCCESS 0L
#undef jp_sf_skype_connector_osx_OSXConnector_ATTACH_PENDING_AUTHORIZATION
#define jp_sf_skype_connector_osx_OSXConnector_ATTACH_PENDING_AUTHORIZATION 1L
#undef jp_sf_skype_connector_osx_OSXConnector_ATTACH_REFUSED
#define jp_sf_skype_connector_osx_OSXConnector_ATTACH_REFUSED 2L
#undef jp_sf_skype_connector_osx_OSXConnector_ATTACH_NOT_AVAILABLE
#define jp_sf_skype_connector_osx_OSXConnector_ATTACH_NOT_AVAILABLE 3L
#undef jp_sf_skype_connector_osx_OSXConnector_ATTACH_API_AVAILABLE
#define jp_sf_skype_connector_osx_OSXConnector_ATTACH_API_AVAILABLE 32769L
/*
 * Class:     jp_sf_skype_connector_osx_OSXConnector
 * Method:    nativeSendMessage
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jp_sf_skype_connector_osx_OSXConnector_nativeSendMessage
  (JNIEnv *, jclass, jstring);

/*
 * Class:     jp_sf_skype_connector_osx_OSXConnector
 * Method:    nativeDestroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_sf_skype_connector_osx_OSXConnector_nativeDestroy
  (JNIEnv *, jclass);

/*
 * Class:     jp_sf_skype_connector_osx_OSXConnector
 * Method:    nativeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jp_sf_skype_connector_osx_OSXConnector_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
